name: Create backup of growi markdown files
on:
  schedule:
    - cron:  '*/10 * * * *'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master

    - name: Install required packages
      run: |
        sudo apt update -y
        sudo apt install -y jq nkf

    - name: Run shell script
      run: bash .github/backup.sh

    - name: Add and commit files
      run: |
        status=$(git status -s)
        if [ "${status}" ]; then
          git add .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes at $(date "+DATE: %Y-%m-%d TIME: %H:%M:%S")" -a
        fi

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}