name: Create backup of growi markdown files
on:
  schedule:
    - cron:  '*/10 * * * *'
  push:
    branches:
      - master

jobs:
  backup:
    name: backup
    runs-on: ubuntu-18.04
    env:
      URL: "https://ymmmtym.growi.cloud"

    steps:
    - uses: actions/checkout@master

    - name: Install required packages
      run: |
        sudo apt update -y
        sudo apt install -y jq nkf

    - name: Check server responce
      run: curl -s ${URL} -o /dev/null -w %{http_code} --connect-timeout 60

    - name: Run shell script
      run: bash .github/backup.sh ${URL}
      if: github.event.head_commit.message == '200'

    - name: Run git status
      run: git status -s

    - name: Add and commit files
      run: |
        export TZ="Asia/Tokyo"
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes at $(date "+DATE: %Y-%m-%d TIME: %H:%M:%S")" -a
      if: github.event.head_commit.message

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      if: github.event.head_commit.message