name: Create backup of growi markdown files
on:
  schedule:
    - cron:  '*/5 * * * *'
  push:
    branches:
      - master

jobs:
  backup:
    name: backup
    runs-on: ubuntu-18.04
    env:
      URL: "https://ymmmtym.growi.cloud"
    if: contains(github.event.head_commit.message, '[ci skip]') == false

    steps:
    - uses: actions/checkout@master

    - name: Install required packages
      run: |
        sudo apt update -y
        sudo apt install -y jq nkf

    - name: Befor check server responce
      id: before
      run: |
        echo "::set-output name=code::$(curl -s -o /dev/null -I -w %{http_code} --connect-timeout 60 ${URL})"
        curl -s -o /dev/null -I -w %{http_code} --connect-timeout 60 ${URL}

    - name: Run shell script
      run: bash .github/backup.sh ${URL}
      if: ${{ steps.before.outputs.code }} == '200'

    - name: After check server responce
      id: after
      run: |
        echo "::set-output name=code::$(curl -s -o /dev/null -I -w %{http_code} --connect-timeout 60 ${URL})"
        curl -s -o /dev/null -I -w %{http_code} --connect-timeout 60 ${URL}

    - name: Run git status
      id: status
      run: |
        echo "::set-output name=status::$(git status -s)"
      if: ${{ steps.after.outputs.code }} == '200'

    - name: Add and commit files
      run: |
        export TZ="Asia/Tokyo"
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes at $(date "+DATE: %Y-%m-%d TIME: %H:%M:%S")"
      if: ${{ steps.status.outputs.status }} 

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      if: ${{ steps.status.outputs.status }}